In [1]:
import numpy as np

In [2]:
k = np.array([[1,2,3],[4,5,6]])

In [3]:
k.shape[0]

2

In [4]:
np.zeros((6,6), dtype = 'int')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [5]:
np.ones((6,6), dtype = 'int')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [6]:
np.eye(6, dtype = 'int')

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [7]:
A = np.random.random((6,6))
A

array([[0.7584782 , 0.56651198, 0.50596154, 0.42184108, 0.54581113,
        0.88264799],
       [0.12320207, 0.07234074, 0.79731519, 0.64990952, 0.15869368,
        0.41981601],
       [0.08321332, 0.28532111, 0.569842  , 0.11294004, 0.3198187 ,
        0.16609298],
       [0.8621649 , 0.00556948, 0.40852318, 0.03649776, 0.09173515,
        0.16323251],
       [0.90739385, 0.44148463, 0.35733273, 0.9166733 , 0.62901545,
        0.3397136 ],
       [0.66026641, 0.81287973, 0.1433937 , 0.87963453, 0.72363947,
        0.94540556]])

In [8]:
A.std()

0.2976053693841351

In [9]:
np.median(A)

0.4316628523929306

In [10]:
k

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
k > 3

array([[False, False, False],
       [ True,  True,  True]])

In [12]:
k[k>3]

array([4, 5, 6])

In [13]:
k.flatten()

array([1, 2, 3, 4, 5, 6])

In [14]:
k.ravel()

array([1, 2, 3, 4, 5, 6])

In [15]:
k.reshape((6,1))
k

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
k.resize((6,1))
k

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [17]:
V = np.array([[51,23,33,42,52,56],[64,55,46,17,28,49]])
W = np.array([[77,21,32,43,82,61],[14,65,56,37,78,29]])

In [18]:
V + W

array([[128,  44,  65,  85, 134, 117],
       [ 78, 120, 102,  54, 106,  78]])

In [19]:
np.add(V, W)

array([[128,  44,  65,  85, 134, 117],
       [ 78, 120, 102,  54, 106,  78]])

In [20]:
V - W

array([[-26,   2,   1,  -1, -30,  -5],
       [ 50, -10, -10, -20, -50,  20]])

In [21]:
np.subtract(V, W)

array([[-26,   2,   1,  -1, -30,  -5],
       [ 50, -10, -10, -20, -50,  20]])

In [22]:
V * W

array([[3927,  483, 1056, 1806, 4264, 3416],
       [ 896, 3575, 2576,  629, 2184, 1421]])

In [23]:
np.multiply(V, W)

array([[3927,  483, 1056, 1806, 4264, 3416],
       [ 896, 3575, 2576,  629, 2184, 1421]])

In [24]:
A = np.random.random((1000,1000))
np.average(A)

0.5000178905975132

In [25]:
B = np.random.random((1000,1000))
np.average(B)

0.4997020058364343

In [26]:
%%time
A * B

Wall time: 14 ms


array([[0.39048642, 0.29519003, 0.65494479, ..., 0.14313703, 0.04570719,
        0.06237201],
       [0.00199972, 0.0047221 , 0.38264646, ..., 0.30091124, 0.23267783,
        0.00540837],
       [0.39465191, 0.48229911, 0.03297027, ..., 0.12920471, 0.59336123,
        0.13696418],
       ...,
       [0.2553968 , 0.72656036, 0.10726126, ..., 0.04424279, 0.26252833,
        0.50664914],
       [0.14355092, 0.16698046, 0.73743983, ..., 0.20883839, 0.01805375,
        0.25265632],
       [0.00702897, 0.18973997, 0.21111873, ..., 0.63601571, 0.48747958,
        0.41364782]])

In [27]:
C = np.linspace(0,10, 50)
C

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [28]:
C = np.arange(0,10, 0.5)
C

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [29]:
k = np.array([[1,2],[4,5]])
l = np.array([[1,2],[5,6]])

In [30]:
k.dot(l)

array([[11, 14],
       [29, 38]])

In [31]:
k @ l

array([[11, 14],
       [29, 38]])