In [1]:
import numpy as np

In [4]:
A = np.array([[3,3,3],[1,3,4],[7,1,3]])
np.unique(A)

array([1, 3, 4, 7])

In [6]:
Z = np.array([92, 13, 44, 555, 1, -3])

In [10]:
Z[::-1][4]

13

In [12]:
O = np.ones(5)
O

array([1., 1., 1., 1., 1.])

In [14]:
T = np.array([2,2,2,2,2])
T

array([2, 2, 2, 2, 2])

In [15]:
O.dot(T)

10.0

In [17]:
A = np.array([[0,9,19,13],[1,20,5,13],[12,11,3,4]])
B = np.array([[2,0,0,0],[1,2,2,0],[2,1,1,0],[0,0,1,1]])
np.diag(A @ B)

array([47, 45, 29])

In [18]:
np.average(np.array([[-1, 33, 4, 1],
[0, 1, 1, 0]]))

4.875

In [19]:
from scipy import linalg

In [20]:
A = np.array([[6, 0, 3], [0,
-1, 2], [12, 3, 0]])
linalg.det(A)

0.0

In [22]:
A = np.array([[1,-1,-1,0],[-1,2,-1,-1],[-1,-1,2,-1],[0,-1,-1,1]])
eigen = linalg.eig(A)[0]
eigen

array([-1.+0.j,  1.+0.j,  3.+0.j,  3.+0.j])

In [25]:
A = np.array([[2,4,0,4,1],[2,4,1,1,0],[1,1,1,2,2],[0,1,3,2,4],[2,2,2,0,2]])
Ainv = linalg.inv(A)
np.sum(np.diag(Ainv))

array([[2, 4, 0, 4, 1],
       [2, 4, 1, 1, 0],
       [1, 1, 1, 2, 2],
       [0, 1, 3, 2, 4],
       [2, 2, 2, 0, 2]])